
[paths]
musi_path = "~/Music" # path where music should be stored and stuff
auto_search_under = "~/"
file_explorer_base_dir = "~/"
musimanager_directory = "~/Music/musimanager" # directory where musimanager can store files

[newpipe]
newpipe_playlists = []
newpipe_bkup_directory = "$paths::musimanager_directory"

[ytmusic_search_limits]
musitracker_search_limit = 75
musitracker_search_limit_first_time = 300

[music_formats]
musi_download_ext = "m4a"
search_exts = ["mp3", "m4a", "flac", "ogg"]

[ascii_art]
force_ascii_art = false # linux only (cuz theres ueberzug too)
disable_ascii_art = true # disabled cuz its crashing with some error which i don't wanna debug rn

[global_shortcuts]
enable_global_shortcuts = false # pip install pynput
pause_global_shortcut = "<cmd>+<F10>" # meta + f10

[random_options] # toggle using "G" menu
show_artist_name_besides_song_name = true
show_hidden_in_file_explorer = false
save_on_exit = true
auto_search_albums = false
debug_prints = false
hide_ueberzug_album_art = false # only works if using this when ueberzug is being used

[general_options]
git_backup_db = false # enable to save the changes made in the db to a git repo

[android_specific]
player_widget_to_browser_widget_height_ratio = [1, 7]

[player]
seek_interval = 10 # seconds
compile_on_every_boot = false # mostly needed for debugging/developing
num_queues = 15 # number of queues that will be cached in the db
